spring.application.name=Emotiate

# DATABASE CONFIGURATION
spring.datasource.url=jdbc:postgresql://localhost:5432/Emotiate_DB
spring.datasource.username=postgres
spring.datasource.password=Password
spring.jpa.hibernate.ddl-auto=update

# JWT CONFIGURATIONS
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=86400000

# JADE CONFIGURATIONS
jade.platform-name= EmotiatePlatform
jade.gui= false

# LLM CONFIGURATIONS
llm.groq.url=https://api.groq.com/openai/v1
llm.groq.api-key=${GROQ_API_KEY}
llm.groq.model=openai/gpt-oss-120b
