spring.application.name=Emotiate

# DATABASE CONFIGURATION
spring.datasource.url=jdbc:postgresql://localhost:5432/Emotiate_DB
spring.datasource.username=postgres
spring.datasource.password=Password
spring.jpa.hibernate.ddl-auto=update

